Repository warehouse-13/hammertime, pull requests merged in 2022-02, with the labels that each got.

#7 chore: Add github action to build and run tests
  .github/workflows/build_and_test_action.yml
  Makefile
Labels: kind/test

#13 feat: Add `clear` command to delete all microvms
  README.md
  go.mod
  go.sum
  main.go
  test/fakeserver/main.go
  test/integration/integration_test.go
Labels: kind/feature

#20 fix: Move clear action under delete --all
  README.md
  main.go
  test/integration/integration_test.go
Labels: kind/improvement

#22 Add ability to get mvm with name and/or namespace
  README.md
  main.go
  test/integration/integration_test.go
Labels: kind/feature

#28 deps: Bump flintlock to alpha.8
  go.mod
  go.sum
  main.go
Labels: kind/dependencies

#30 Add release target to cross-compile bins
  .gitignore
  Makefile
  README.md
Labels: kind/build, kind/docs
